image: ruby:2.5

rspec:
  script:
    - gem install bundler
    - bundle install
    - bundle exec rake spec

rubocop:
  script:
    - gem install bundler
    - bundle install
    - bundle exec rubocop

package-to-github:
  stage: deploy
  script:
    - mkdir ~/.gem
    - 'echo ":github: Bearer $GH_PACKAGE_REGISTRY_KEY" > ~/.gem/credentials'
    - chmod 0600 ~/.gem/credentials
    - gem install bundler
    - bundle install
    - bundle exec rake build
    - 'gem push --key github --host https://rubygems.pkg.github.com/Skudo pkg/`ls -1t pkg | head -1`'
  only:
    - tags

package-to-rubygems:
  stage: deploy
  script:
    - mkdir ~/.gem
    - 'echo ":rubygems_api_key: $RUBYGEMS_KEY" > ~/.gem/credentials'
    - chmod 0600 ~/.gem/credentials
    - gem install bundler
    - bundle install
    - bundle exec rake build
    - 'gem push pkg/`ls -1t pkg | head -1`'
  only:
    - tags
