rspec:
  image: ruby:2.5
  script:
    - gem install bundler
    - bundle install
    - bundle exec rake spec

rubocop:
  image: ruby:2.5
  script:
    - gem install bundler
    - bundle install
    - bundle exec rubocop
