rspec:
  image: ruby:2.5
  script:
    - gem install bundler
    - bundle install
    - bundle exec rake spec

rubocop:
  image: ruby:2.5
  script:
    - gem install bundler
    - bundle install
    # TODO: Add documentation and remove the Style/Documentation exception.
    - bundle exec rubocop --except Style/Documentation
