AllCops:
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/factories/*.rb'

Naming/FileName:
  Exclude:
    - lib/shark-on-lambda.rb
    - spec/shark-on-lambda_spec.rb

# TODO: Add documentation and remove the Style/Documentation exception.
Style/Documentation:
  Enabled: false
