---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.3

install:
  - gem install bundler -v 1.17.2
  - bundle install

script:
  - bundle exec rake spec
  # TODO: Add documentation and remove the Style/Documentation exception.
  - bundle exec rubocop --except Style/Documentation .
