default:
  host: apigateway.aws.com
  port: 443

development:
  host: localhost
  port: 8080
  credentials:
    username: 'test'

staging:
  host: staging.example.com
  port: 443

test:
  cache_durations:
    default: 180
    known_item: 60

  host: test.example.com
  port: 8443

production:
  host: example.com
  port: 443
