name: Push Gem
on:
  push:
    tags:
      - 'v*'

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Run RSpec
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rspec

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Run rubocop
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rubocop

  push-gem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Build gem
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake build
      - name: Push to GitHub Package Repository
        run: |
          mkdir -p $HOME/.gem
          echo ":github: Bearer $GEM_HOST_API_KEY" >> $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          bundle exec rake build
          gem push --key github --host https://rubygems.pkg.github.com/Skudo pkg/`ls -1t pkg | head -1`
        env:
          GEM_HOST_API_KEY: ${{secrets.GITHUB_AUTH_TOKEN}}
          OWNER: username
      - name: Push to RubyGems
        run: |
          mkdir -p $HOME/.gem
          echo ":rubygems_api_key: $GEM_HOST_API_KEY" >> ~/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          bundle exec rake build
          gem push pkg/`ls -1t pkg | head -1`
        env:
          GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
